# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from pathlib import Path

import resources_rc

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLayout,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QStackedWidget, QStatusBar, QVBoxLayout, QWidget)


def _load_pixmap(relative_path, fallback_resource=None):
        candidate = Path(__file__).resolve().parent.joinpath(*relative_path)
        if candidate.is_file():
                return QPixmap(str(candidate))
        if fallback_resource:
                return QPixmap(fallback_resource)
        return QPixmap()


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        if not QMainWindow.objectName():
            QMainWindow.setObjectName(u"QMainWindow")
        QMainWindow.resize(1200, 1100)
        QMainWindow.setMouseTracking(False)
        icon = QIcon("icons/atg_logo.jpg")
        QMainWindow.setWindowIcon(icon)
        QMainWindow.setAutoFillBackground(False)
        QMainWindow.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.528, y1:0.34, x2:1, y2:1, stop:0 rgba(63, 159, 219, 255), stop:0.579545 rgba(253, 255, 255, 255));")
        QMainWindow.setAnimated(True)
        self.centralwidget = QWidget(QMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.side_bar = QWidget(self.centralwidget)
        self.side_bar.setObjectName(u"side_bar")
        self.side_bar.setGeometry(QRect(0, 110, 261, 931))
        self.side_bar.setStyleSheet(u"background-color: rgb(0, 84, 252);")
        self.load_model_btn = QPushButton(self.side_bar)
        self.load_model_btn.setObjectName(u"load_model_btn")
        self.load_model_btn.setGeometry(QRect(40, 160, 171, 61))
        font = QFont()
        font.setFamilies([u"Verdana"])
        font.setPointSize(14)
        font.setBold(True)
        self.load_model_btn.setFont(font)
        self.load_model_btn.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        icon1 = QIcon(u":/icons/icons/open_file.svg")
        self.load_model_btn.setIcon(icon1)
        self.load_model_btn.setIconSize(QSize(25, 25))
        self.load_model_btn.setCheckable(True)
        self.cut_process_btn = QPushButton(self.side_bar)
        self.cut_process_btn.setObjectName(u"cut_process_btn")
        self.cut_process_btn.setGeometry(QRect(40, 230, 171, 61))
        self.cut_process_btn.setFont(font)
        self.cut_process_btn.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        icon2 = QIcon("icons/scissor_logo.png")
        self.cut_process_btn.setIcon(icon2)
        self.cut_process_btn.setIconSize(QSize(25, 25))
        self.cut_process_btn.setCheckable(True)
        self.database_btn = QPushButton(self.side_bar)
        self.database_btn.setObjectName(u"database_btn")
        self.database_btn.setGeometry(QRect(40, 300, 171, 61))
        self.database_btn.setFont(font)
        self.database_btn.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        icon3 = QIcon("icons/database_log.png")
        self.database_btn.setIcon(icon3)
        self.database_btn.setIconSize(QSize(25, 25))
        self.database_btn.setCheckable(True)
        self.simulation_btn = QPushButton(self.side_bar)
        self.simulation_btn.setObjectName(u"simulation_btn")
        self.simulation_btn.setGeometry(QRect(40, 370, 171, 61))
        self.simulation_btn.setFont(font)
        self.simulation_btn.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        icon4 = QIcon(u":/icons/icons/play_button.svg")
        self.simulation_btn.setIcon(icon4)
        self.simulation_btn.setIconSize(QSize(25, 25))
        self.simulation_btn.setCheckable(True)
        self.end_btn = QPushButton(self.side_bar)
        self.end_btn.setObjectName(u"end_btn")
        self.end_btn.setGeometry(QRect(40, 800, 161, 61))
        self.end_btn.setFont(font)
        self.end_btn.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        icon5 = QIcon.fromTheme(u"system-shutdown", QIcon(u":/icons/icons/home.svg"))
        self.end_btn.setIcon(icon5)
        self.end_btn.setIconSize(QSize(25, 25))
        self.end_btn.setCheckable(True)
        self.end_btn.setChecked(False)
        self.Menu_btn = QPushButton(self.side_bar)
        self.Menu_btn.setObjectName(u"Menu_btn")
        self.Menu_btn.setGeometry(QRect(40, 90, 171, 61))
        self.Menu_btn.setFont(font)
        self.Menu_btn.setStyleSheet(u"color: rgb(0, 85, 255);\n"
"background-color: rgb(255, 255, 255);")
        icon6 = QIcon(u":/icons/icons/home.svg")
        self.Menu_btn.setIcon(icon6)
        self.Menu_btn.setIconSize(QSize(25, 25))
        self.Menu_btn.setCheckable(True)
        self.Menu_btn.setChecked(False)
        self.Menu_btn.setAutoDefault(False)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1221, 111))
        self.frame.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.943, y1:0.518, x2:0.284227, y2:0.529, stop:0.136364 rgba(54, 208, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.atg_logo_image = QLabel(self.frame)
        self.atg_logo_image.setObjectName(u"atg_logo_image")
        self.atg_logo_image.setGeometry(QRect(0, 10, 301, 101))
        self.atg_logo_image.setAutoFillBackground(False)
        self.atg_logo_image.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.atg_logo_image.setFrameShape(QFrame.Shape.Panel)
        self.atg_logo_image.setFrameShadow(QFrame.Shadow.Sunken)
        self.atg_logo_image.setPixmap(_load_pixmap(("..", "atg_logo.jpg"), "icons/atg_logo.jpg"))
        self.atg_logo_image.setScaledContents(True)
        self.atg_logo_image.setMargin(0)
        self.atg_logo_image.setOpenExternalLinks(False)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(350, 20, 501, 41))
        font1 = QFont()
        font1.setFamilies([u"Verdana"])
        font1.setPointSize(18)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(320, 10, 20, 91))
        self.line.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(350, 60, 501, 21))
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(260, 110, 951, 931))
        self.stackedWidget.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.899, stop:0 rgba(0, 195, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.load_model_page = QWidget()
        self.load_model_page.setObjectName(u"load_model_page")
        self.load_model = QPushButton(self.load_model_page)
        self.load_model.setObjectName(u"load_model")
        self.load_model.setGeometry(QRect(140, 50, 221, 61))
        font2 = QFont()
        font2.setFamilies([u"Verdana"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.load_model.setFont(font2)
        self.load_model.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.load_model.setIcon(icon6)
        self.load_model.setIconSize(QSize(25, 25))
        self.load_model.setCheckable(True)
        self.openGLWidget = QOpenGLWidget(self.load_model_page)
        self.openGLWidget.setObjectName(u"openGLWidget")
        self.openGLWidget.setGeometry(QRect(140, 550, 651, 351))
        self.model_path = QLabel(self.load_model_page)
        self.model_path.setObjectName(u"model_path")
        self.model_path.setGeometry(QRect(490, 60, 301, 41))
        self.model_path.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.widget = QWidget(self.load_model_page)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(540, 250, 251, 271))
        self.widget.setStyleSheet(u"background-color: rgb(103, 218, 254);")
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.set_x_model = QLabel(self.widget)
        self.set_x_model.setObjectName(u"set_x_model")
        self.set_x_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_x_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_x_model)

        self.set_y_model = QLabel(self.widget)
        self.set_y_model.setObjectName(u"set_y_model")
        self.set_y_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_y_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_y_model)

        self.set_z_model = QLabel(self.widget)
        self.set_z_model.setObjectName(u"set_z_model")
        self.set_z_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_z_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_z_model)

        self.set_yaw_model = QLabel(self.widget)
        self.set_yaw_model.setObjectName(u"set_yaw_model")
        self.set_yaw_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_yaw_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_yaw_model)

        self.set_pitch_model = QLabel(self.widget)
        self.set_pitch_model.setObjectName(u"set_pitch_model")
        self.set_pitch_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_pitch_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_pitch_model)

        self.set_roll_model = QLabel(self.widget)
        self.set_roll_model.setObjectName(u"set_roll_model")
        self.set_roll_model.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.set_roll_model.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)

        self.verticalLayout_2.addWidget(self.set_roll_model)

        self.label_19 = QLabel(self.load_model_page)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(540, 210, 251, 31))
        self.label_19.setFont(font2)
        self.label_19.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame1 = QFrame(self.load_model_page)
        self.frame1.setObjectName(u"frame1")
        self.frame1.setGeometry(QRect(140, 210, 281, 311))
        self.frame1.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.parametry_modelu_layout = QVBoxLayout(self.frame1)
        self.parametry_modelu_layout.setSpacing(9)
        self.parametry_modelu_layout.setObjectName(u"parametry_modelu_layout")
        self.parametry_modelu_layout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.label_18 = QLabel(self.frame1)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_18)

        self.label_5 = QLabel(self.frame1)
        self.label_5.setObjectName(u"label_5")
        font3 = QFont()
        font3.setFamilies([u"Verdana"])
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setItalic(True)
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"background-color: rgb(194, 233, 232);\n"
"background-color: rgb(103, 219, 255);")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_5)

        self.label_6 = QLabel(self.frame1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_6)

        self.label_7 = QLabel(self.frame1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_7)

        self.label_8 = QLabel(self.frame1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_8)

        self.label_9 = QLabel(self.frame1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_9)

        self.label_10 = QLabel(self.frame1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"background-color: rgb(103, 219, 255);")
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.parametry_modelu_layout.addWidget(self.label_10)

        self.stackedWidget.addWidget(self.load_model_page)
        self.cut_process = QWidget()
        self.cut_process.setObjectName(u"cut_process")
        self.openGLWidget_2 = QOpenGLWidget(self.cut_process)
        self.openGLWidget_2.setObjectName(u"openGLWidget_2")
        self.openGLWidget_2.setGeometry(QRect(110, 480, 731, 421))
        self.widget_2 = QWidget(self.cut_process)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(110, 70, 731, 191))
        self.widget_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_4 = QLabel(self.widget_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 10, 211, 31))
        font4 = QFont()
        font4.setFamilies([u"Verdana"])
        font4.setPointSize(11)
        font4.setBold(True)
        self.label_4.setFont(font4)
        self.label_4.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.widget_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(140, 60, 101, 16))
        font5 = QFont()
        font5.setFamilies([u"Verdana"])
        font5.setPointSize(10)
        font5.setBold(True)
        self.label_11.setFont(font5)
        self.line_2 = QFrame(self.widget_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(350, 40, 41, 121))
        self.line_2.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_12 = QLabel(self.widget_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(530, 60, 101, 16))
        self.label_12.setFont(font5)
        self.sken_zleva_pravo = QRadioButton(self.widget_2)
        self.sken_zleva_pravo.setObjectName(u"sken_zleva_pravo")
        self.sken_zleva_pravo.setGeometry(QRect(50, 90, 201, 24))
        self.sken_zprava_doleva = QRadioButton(self.widget_2)
        self.sken_zprava_doleva.setObjectName(u"sken_zprava_doleva")
        self.sken_zprava_doleva.setGeometry(QRect(50, 130, 201, 24))
        self.sken_nahoru_dolu = QRadioButton(self.widget_2)
        self.sken_nahoru_dolu.setObjectName(u"sken_nahoru_dolu")
        self.sken_nahoru_dolu.setGeometry(QRect(430, 90, 201, 24))
        self.sken_dolu_nahoru = QRadioButton(self.widget_2)
        self.sken_dolu_nahoru.setObjectName(u"sken_dolu_nahoru")
        self.sken_dolu_nahoru.setGeometry(QRect(430, 130, 201, 24))
        self.widget_3 = QWidget(self.cut_process)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(110, 290, 731, 81))
        self.widget_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_13 = QLabel(self.widget_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 10, 211, 31))
        self.label_13.setFont(font4)
        self.label_13.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_14 = QLabel(self.widget_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(50, 50, 341, 16))
        font6 = QFont()
        font6.setFamilies([u"Verdana"])
        font6.setBold(True)
        self.label_14.setFont(font6)
        self.set_krok = QLabel(self.widget_3)
        self.set_krok.setObjectName(u"set_krok")
        self.set_krok.setGeometry(QRect(480, 50, 201, 20))
        self.set_krok.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextEditable)
        self.stackedWidget.addWidget(self.cut_process)
        self.menu_page = QWidget()
        self.menu_page.setObjectName(u"menu_page")
        self.new_project_btn = QPushButton(self.menu_page)
        self.new_project_btn.setObjectName(u"new_project_btn")
        self.new_project_btn.setGeometry(QRect(160, 210, 251, 111))
        font7 = QFont()
        font7.setFamilies([u"Verdana"])
        font7.setPointSize(15)
        font7.setBold(False)
        self.new_project_btn.setFont(font7)
        self.new_project_btn.setStyleSheet(u"background-color: rgb(255, 170, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(154, 219, 217, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);\n"
"selection-color: rgb(85, 255, 0);\n"
"alternate-background-color: rgb(255, 170, 0);")
        icon7 = QIcon.fromTheme(u"document-new", QIcon(u":/icons/icons/open_file.svg"))
        self.new_project_btn.setIcon(icon7)
        self.new_project_btn.setIconSize(QSize(30, 30))
        self.exist_project_btn = QPushButton(self.menu_page)
        self.exist_project_btn.setObjectName(u"exist_project_btn")
        self.exist_project_btn.setGeometry(QRect(540, 210, 251, 111))
        font8 = QFont()
        font8.setFamilies([u"Verdana"])
        font8.setPointSize(16)
        self.exist_project_btn.setFont(font8)
        self.exist_project_btn.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(154, 219, 217, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 85, 255);")
        self.exist_project_btn.setIcon(icon1)
        self.exist_project_btn.setIconSize(QSize(30, 30))
        self.label = QLabel(self.menu_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 500, 631, 351))
        self.label.setPixmap(_load_pixmap(("..", "vana_scanmaster.jpg"), "icons/vana_scanmaster.jpg"))
        self.label.setScaledContents(True)
        self.stackedWidget.addWidget(self.menu_page)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(QMainWindow)
        self.statusbar.setObjectName(u"statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)
        self.end_btn.clicked.connect(QMainWindow.close)
        self.load_model_btn.clicked.connect(self.stackedWidget.show)
        self.cut_process_btn.toggled.connect(self.stackedWidget.show)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(QMainWindow)
    # setupUi

    def retranslateUi(self, QMainWindow):
        QMainWindow.setWindowTitle(QCoreApplication.translate("QMainWindow", u"ATG NAVI - generator", None))
        self.load_model_btn.setText(QCoreApplication.translate("QMainWindow", u"Load model", None))
        self.cut_process_btn.setText(QCoreApplication.translate("QMainWindow", u"Cut process", None))
        self.database_btn.setText(QCoreApplication.translate("QMainWindow", u"Database", None))
        self.simulation_btn.setText(QCoreApplication.translate("QMainWindow", u"Simulation", None))
        self.end_btn.setText(QCoreApplication.translate("QMainWindow", u"End", None))
        self.Menu_btn.setText(QCoreApplication.translate("QMainWindow", u"Menu", None))
        self.atg_logo_image.setText("")
        self.label_2.setText(QCoreApplication.translate("QMainWindow", u"NAVI - GENER\u00c1TOR TRAJEKTORI\u00cd ", None))
        self.label_3.setText(QCoreApplication.translate("QMainWindow", u"N\u00e1stroj pro generov\u00e1n\u00ed trajektorie a simulaci", None))
        self.load_model.setText(QCoreApplication.translate("QMainWindow", u"OTEV\u0158\u00cdT MODEL", None))
        self.model_path.setText(QCoreApplication.translate("QMainWindow", u"TextLabel", None))
        self.set_x_model.setText("")
        self.set_y_model.setText("")
        self.set_z_model.setText("")
        self.set_yaw_model.setText("")
        self.set_pitch_model.setText("")
        self.set_roll_model.setText("")
        self.label_19.setText(QCoreApplication.translate("QMainWindow", u"HODNOTY ", None))
        self.label_18.setText(QCoreApplication.translate("QMainWindow", u"PARAMETRY MODELU", None))
        self.label_5.setText(QCoreApplication.translate("QMainWindow", u"Poloha modelu v ose X [mm]", None))
        self.label_6.setText(QCoreApplication.translate("QMainWindow", u"Poloha modelu v ose Y [mm]", None))
        self.label_7.setText(QCoreApplication.translate("QMainWindow", u"Poloha modelu v ose Z [mm]", None))
        self.label_8.setText(QCoreApplication.translate("QMainWindow", u"Orientace modelu YAW [\u00b0]", None))
        self.label_9.setText(QCoreApplication.translate("QMainWindow", u"Orientace modelu PITCH [\u00b0]", None))
        self.label_10.setText(QCoreApplication.translate("QMainWindow", u"Orientace modelu ROLL [\u00b0]", None))
        self.label_4.setText(QCoreApplication.translate("QMainWindow", u"Skenovac\u00ed strategie", None))
        self.label_11.setText(QCoreApplication.translate("QMainWindow", u"Vn\u011bj\u0161\u00ed sken", None))
        self.label_12.setText(QCoreApplication.translate("QMainWindow", u"Vnit\u0159n\u00ed sken", None))
        self.sken_zleva_pravo.setText(QCoreApplication.translate("QMainWindow", u"Skenov\u00e1n\u00ed zleva do prava", None))
        self.sken_zprava_doleva.setText(QCoreApplication.translate("QMainWindow", u"Skenov\u00e1n\u00ed z prava do leva", None))
        self.sken_nahoru_dolu.setText(QCoreApplication.translate("QMainWindow", u"Skenov\u00e1n\u00ed ze shora dol\u016f", None))
        self.sken_dolu_nahoru.setText(QCoreApplication.translate("QMainWindow", u"Skenov\u00e1n\u00ed ze spodu nahoru", None))
        self.label_13.setText(QCoreApplication.translate("QMainWindow", u"Skenovac\u00ed krok", None))
        self.label_14.setText(QCoreApplication.translate("QMainWindow", u"Krok mezi dv\u011bma po sob\u011b skenovac\u00edmi body [mm]", None))
        self.set_krok.setText(QCoreApplication.translate("QMainWindow", u"0.5", None))
#if QT_CONFIG(tooltip)
        self.new_project_btn.setToolTip(QCoreApplication.translate("QMainWindow", u"<html><head/><body><p>Vytvo\u0159\u00ed se nov\u00e1 trajektorie pro konkr\u00e9tn\u00ed d\u00edl</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.new_project_btn.setText(QCoreApplication.translate("QMainWindow", u"NEW GENERATOR", None))
#if QT_CONFIG(tooltip)
        self.exist_project_btn.setToolTip(QCoreApplication.translate("QMainWindow", u"<html><head/><body><p><span style=\" font-size:9pt;\">Otestuje se ji\u017e vytvo\u0159en\u00e1 trajektorie</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.exist_project_btn.setText(QCoreApplication.translate("QMainWindow", u"OPEN GENERATOR", None))
        self.label.setText("")
    # retranslateUi

